### ISSUE TITLE
Where would services fit in?

### ISSUE THREAD

**Issue by fjbaldon** [jakubnabrdalik/hentai#11]
Thanks for publishing an amazing repo for learning. I just have some few questions. Do service classes exist in hexagonal architecture? If so, how would they fit in the directory and the overall data flow structure? Can facades depend on services? Thanks in advance.

**Comment by jakubnabrdalik** [comment]
So here's how it works.
Let's define first what you mean by "service" classes. In "Domain Driven Design" by Eric Evans there are 3 types of Service classes.

1. Application layer Service class - It's an entry point to the Bounded Context. This is your Facade class.

2. Domain layer Services - this is a class which is not representing any DATA kept in the database, but rather it's performing a function (or handling part of a process). Those classes are never "stored" in a database, they are *usually* stateless due to multithreading of web apps (but can be done otherwise in a single kafka consumer). An exemple here would be the Film Creator.

3. Infrastructure layer Service (and interface) - these are FilmRepository and it's implementations.

There's one thing to remember: NEVER add a "*Service" suffix to service classes. "Service" means nothing or everything (3 different things in DDD) and thus it is not very usefull to the reader.

Therefore I  do not have a single class ending in "Service" suffix in my apps, no matter the architecture style or language.

**Comment by fjbaldon** [comment]
I see, that's why there's no *Service classes. In your Facade class, both the add and show methods are in one class, is this CQRS? In also what way is hexagonal architecture being used here?

**Comment by fjbaldon** [comment]
I see, that's why there's no *Service classes. In your Facade class, both the add and show methods are in one class, is this CQRS? In also what way is hexagonal architecture being used here?

**Comment by jakubnabrdalik** [comment]
CQRS is when you split the whole flow for Command and for Query. So this is not a good example.

In DDD Application Service (facade) should be rather thin - just pass over to the proper domain, usually handling transactions etc. However in this example the code is so trivial that there's no point in making more classes.

As for Hexagonal Architecture, see this: https://jakubn.gitlab.io/keepitclean/#1
